version = "1.0"

[main]
name = "Main Settings"
services = ["matrix-__APP__"]

    [main.welcome]
    name = "Experience for new Users"

        [main.welcome.enable_registration]
        ask = "Enable Registration for new users."
        type = "boolean"
        yes = true
        no = false
        help = "Defaults to 'false'. If 'true', it is highly recommended to use either captcha, email, or token-based verification to avoid SPAM."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

        [main.welcome.password_enabled]
        ask = "Enable Password Login?"
        type = "boolean"
        yes = true
        no = false
        help = "If disabled, Login with Non-YunoHost Users impossible. But it simplies Login process if your Matrix server only has YunoHost SSO Users."
        bind = "password_config>enabled:/etc/matrix-__APP__/homeserver.yaml"
        visible = "! enable_registration"

        [main.welcome.registrations_require_3pid]
        ask = "Register only with all following types of 3PID."
        type = "select"
        choices = ["false","email", "msidn", "email&msisdn"]
        help = "Defaults to: 'email'. Phone number: 'msisdn'"
        visible = "enable_registration"

        [main.welcome.allowed_local_3pids]
        ask = "Register only with given formats of 3PIDs."
        type = "string"
        help = '''
        allowed_local_3pids:
          - medium: email
            pattern: '^[^@]+@matrix\.org$'
          - medium: msisdn
            pattern: '\+33'
        '''
        visible = "registrations_require_3pid != 'false'"

        [main.welcome.auto_join_rooms]
        ask = "Auto Join new Users in following Rooms:"
        type = "string"
        help = "Users who register on this homeserver will automatically be joined to these rooms. If the room already exists, the join rule must be set to 'public'. See also next setting."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

        [main.welcome.autocreate_auto_join_rooms]
        ask = "Auto-Create room for Auto Join if not existing?"
        type = "boolean"
        yes = true
        no = false
        help = "Setting to false means that if the rooms are not manually created, users cannot be auto-joined. Auto-created rooms will be public and federated by default, this can be customised in CLI with the settings auto_join_*."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

        [main.welcome.notif_for_new_users]
        ask = "Enable email notifications for new users?"
        type = "boolean"
        yes = true
        no = false
        help = "Defaults to 'true'."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"
        visible = "enable_notifs"

    [main.privacy]
    name = "Data Privacy"
    
        [main.privacy.text]
        ask = '''
        * "all": any locally-created room
        * "invite": any room created with the "private_chat" or "trusted_private_chat" room creation presets
        * "off": No encryption by default
        '''
        type = "markdown"

        [main.privacy.e2e_enabled_by_default]
        ask = "End-to-End Encryption by default for locally-created Rooms"
        type = "select"
        choices = ["all", "invite", "off"]
        help = "Note that encryption can always be turned on manually, even after creation."
        bind = "encryption_enabled_by_default_for_room_type:/etc/matrix-__APP__/homeserver.yaml"
        
        [main.privacy.allow_public_rooms_over_federation]
        ask = "Access Public Rooms Directory over Federation?"
        type = "boolean"
        yes = true
        no = false
        help = "Disabled by default. If disabled, users on other homeserver will not be able to look for a public room on your homeserver. They will have to type the ID of the room to join."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

        [main.privacy.disable_msisdn_registration]
        ask = "Disable asking Phone Number in Registration flow."
        type = "boolean"
        yes = true
        no = false
        help = "Overrides 3PID settings if MSISDNs are set as required."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"
        visible = "enable_registration"

    [main.experience]
    name = "User Experience"

        [main.experience.web_client_location]
        ask = "URL to the web client which / will redirect to."
        type = "url"
        help = "Basically Element instance the server should redirect to."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

        [main.experience.enable_group_creation]
        ask = "Allow non-server-admin Users to create Spaces?"
        type = "boolean"
        yes = true
        no = false
        help = "Defaults to 'false'."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

        [main.experience.enable_notifs]
        ask = "Enable sending emails for messages the user missed?"
        type = "boolean"
        yes = true
        no = false
        help = "Defaults to 'false'."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

        [main.experience.client_base_url]
        ask = "URL for client links within the email notifications."
        type = "url"
        help = "Used to be called 'riot_base_url', still supported"
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

[resources]
name = "Resource Usage"
services = ["matrix-__APP__", "nginx"]

    [resources.media]
    name = "Manage Media growth and clean-up"

        [resources.media.max_upload_size]
        ask = "Largest allowed media upload size in bytes."
        type = "string"
        help = "Defaults to: '10M' ."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

[advanced]
name = "Advanced Settings"
services = ["matrix-__APP__"]

    [advanced.help]
    name = "ONLY CHANGE THIS IF YOU'RE AN EXPERT IN SERVER ADMINISTRATION"

        [advanced.help.text]
        ask = '''
        **There are security and privacy risks if you change these settings without knowing what you do!**
        '''
        type = "markdown"

    [advanced.others]
    name = "Others"

            [advanced.others.backup_before_upgrade]
            ask = "Backup before upgrade?"
            type = "boolean"
            yes = true
            no = false
            help = "!!If disabled, do a manual backup before upgrade!! Enable if your Synapse instance is huge and you prefer to disable the backup that is normally automatically done before each upgrade."

            [advanced.others.server_statistics]
            ask = "Server statistics"
            type = "boolean"
            yes = true
            no = false
            help = "Enable to send anonymous statistics to Synapse Developers to improve performance."
            bind = "report_stats:/etc/matrix-__APP__/homeserver.yaml"

    [advanced.guests]
    name = "Experience for Guests / Anonymous"

        [advanced.guests.invite_client_location]
        ask = "Web client location to direct users to during an invite."
        type = "url"
        help = "This is passed to the identity server as the org.matrix.web_client_location key. Defaults to unset, giving no guidance to the identity server."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

        [advanced.guests.allow_guest_access]
        ask = "Allow Users to Register as Guests?"
        type = "boolean"
        yes = true
        no = false
        help = "Guests can participate on this server in rooms with guest access enabled, without a password/email/etc."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

        [advanced.guests.auto_join_rooms_for_guests]
        ask = "Enable Auto Join Room for Guests?"
        type = "boolean"
        yes = true
        no = false
        help = "Defaults to 'true'."
        bind = ":/etc/matrix-__APP__/homeserver.yaml"

    [advanced.privacy]
    name = "Data Privacy"

            [advanced.privacy.default_identity_server]
            ask = "Identity server suggested to clients?"
            type = "url"
            help = "By default, no suggestion is made, so it is left up to the client."
            bind = ":/etc/matrix-__APP__/homeserver.yaml"

            [advanced.privacy.allow_public_rooms_without_auth]
            ask = "Access Public Rooms Directory without authentification?"
            type = "boolean"
            yes = true
            no = false
            help = "Disabled by default. If enabled, anyone can query the Public Rooms Directory (access through the client API). This only makes sense if you want everyone to be able to scroll your public room to see what's interesting on your Homeserver"
            bind = ":/etc/matrix-__APP__/homeserver.yaml"

    [advanced.registration]
    name = "Account Registration"

            [advanced.registration.registration_shared_secret]
            ask = "Shared Secret for Registration."
            type = "string"
            help = "Allows registration of standard or admin accounts, even if Registration disabled."
            bind = ":/etc/matrix-__APP__/homeserver.yaml"

            [advanced.registration.turn_allow_guests]
            ask = "Should guests be allowed to use the TURN server?"
            type = "boolean"
            yes = true
            no = false
            help = "This defaults to True, otherwise VoIP will be unreliable for guests. However, it does introduce a slight security risk as it allows users to connect to arbitrary endpoints without having first signed up for a valid account (e.g. by passing a CAPTCHA)."
            bind = ":/etc/matrix-__APP__/homeserver.yaml"
